const Types = {
  LIST_REQUEST: '@didNumbers/LIST_REQUEST',
  LIST_FAILURE: '@didNumbers/LIST_FAILURE',
  LIST_SUCCESS: '@didNumbers/LIST_SUCCESS',

  CREATE_REQUEST: '@didNumbers/CREATE_REQUEST',
  CREATE_FAILURE: '@didNumbers/CREATE_FAILURE',
  CREATE_SUCCESS: '@didNumbers/CREATE_SUCCESS',

  UPDATE_REQUEST: '@didNumbers/UPDATE_REQUEST',
  UPDATE_FAILURE: '@didNumbers/UPDATE_FAILURE',
  UPDATE_SUCCESS: '@didNumbers/UPDATE_SUCCESS',

  DELETE_REQUEST: '@didNumbers/DELETE_REQUEST',
  DELETE_FAILURE: '@didNumbers/DELETE_FAILURE',
  DELETE_SUCCESS: '@didNumbers/DELETE_SUCCESS',
};

export default Types;
